### PR TITLE
find executable fix

### PR DESCRIPTION
**Pull request by faph**
minor fixes

### CODE REVIEW

**Comment by faph** [comment]
Not sure why the build is failing though!

**Comment by faph** [comment]
Sorry realised that you probably want to fall back on the default `/bin/sh -c' run_with

**Comment by pelson** [comment]
Does this work for you? I'm pretty happy with this, and would happily polish it for merge to master if so.

**Comment by faph** [comment]
Perfect @pelson ! All working fine.

I really like conda execute, btw.

**Comment by pelson** [comment]
> I really like conda execute, btw.

Thanks! I can't believe how useful I'm finding it - everything I do that needs an environment is being conda-executed at the moment. Fast and reproducible :+1:

**Pull request merged**
