### PR TITLE
Locked now makes sure parent dir exists

### LINKED ISSUE #35: Locked implementation broken by conda 4.2 changes
The `conda-execute`'s relied in an implementation detail of former implementation of conda's `Locked` that always created parent directories when they didn't exist. However now [it raises in that scenario](https://github.com/conda/conda/blob/71a15ef21499a6117529d0c8068ca14c7b209267/conda/lock.py#L119).

I'm going to push a PR with the fix, to make sure parent folder of locked directory by `conda-execute` exists.

### PR DESCRIPTION
**Pull request by fogo**
Fixes #35

### CODE REVIEW

**Comment by scopatz** [comment]
I think that this is related to the breakage we are seeing on the conda-forge docs, conda-forge/conda-forge.github.io#287 @pelson @conda-forge/core @ocefpaf @ericdill, is there anyway that we can get this merged?

**Comment by scopatz** [comment]
Yeah, I don't have merge rights here either... Thanks though @ericdill!

**Comment by ocefpaf** [comment]
Only @pelson has. But you will have better chances pinging him on twitter.
Getting his attention using GitHub notification is as hard as getting
tickets to Hamilton.

On Dec 13, 2016 9:15 PM, "Eric Dill" <notifications@github.com> wrote:

*@ericdill* approved this pull request.

LGTM, but I don't have merge rights here or on conda-forge so I'm not that
useful here

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pelson/conda-execute/pull/36#pullrequestreview-12810146>,
or mute the thread

**Comment by scopatz** [comment]
Roger that! I will try the twitter route.

**Comment by pelson** [comment]
Awesome! 👍

**Comment by ocefpaf** [comment]
@pelson I was going to prepare a patch for the feedstock but now that you merged this should I wait for a new release or should I go ahead with the patch?

**Comment by pelson** [comment]
I have cut v0.8 and it should become available once the CI kicks in. xref https://github.com/conda-forge/conda-execute-feedstock/pull/13.

**Pull request merged**
