### PR TITLE
WIP: Add conda 4.3 support

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/pelson/conda-execute/issues/41

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please advise here @kalefranz? Looking at the code in `conda`, I'm not entirely sure what the right way is to move this forward.

In particular, this [block of code]( https://github.com/pelson/conda-execute/blob/v0.8.0/conda_execute/tmpenv.py#L86-L93 ) somehow needs to be rewritten. While I'm not super familiar with the code in this tool, it looks like this is trying to facilitate the download and install of packages into a temporary directory where the magic of `conda-execute` happens. Is there some API we should be using to accomplish this instead?

**Comment by jakirkham** [comment]
To provide context, @kalefranz, `conda-execute` is used to run basically everything service at conda-forge. Updating the feedstocks on the webpage, updating the feedstocks repo, running the linter, running the re-rendering service, running the pinning service, and, hopefully soon, a PyPI update service for Python packages. So it is pretty important that we keep `conda-execute` functioning with newer `conda` releases. Any help you can provide in this direction is greatly appreciated.

**Comment by kalefranz** [comment]
Hi @jakirkham.  Happy to help.  First thing... In the `.travis.yml` file, can you make the scripts section be

```
script:
  - conda execute --help
  - python -c "import conda_execute; print(conda_execute.__version__)"
  - python -c "import conda; print(conda.__version__)"
  - python -m conda info
  - ./tests/run_tests.sh
```

Just the addition of two lines for conda.  That'll help with debugging.

**Comment by jakirkham** [comment]
Great, thanks. No problem. Added in the last commit.

Appears to be `conda` 4.3.21 in a `python` 3.6.1 environment. Reference to one of the builds' info below.

ref: https://travis-ci.org/pelson/conda-execute/jobs/243360511#L331

**Comment by kalefranz** [comment]
I'm working on this right now.  Working on a PR that uses the same [`conda_interface`](https://github.com/conda/conda-build/blob/master/conda_build/conda_interface.py) pattern that conda-build uses.  That should help smooth all the issues over now, and also help make updates of conda easier in the future.

**Comment by kalefranz** [comment]
I'll probably just submit it as a new PR to this repo, rather than a PR to your PR, so that we can have CI run against it.  Sound like a plan?

**Comment by kynan** [comment]
Do you have commit access to this repo @jakirkham? Seems @pelson has totally gone into hiding.

**Comment by kalefranz** [comment]
If not, I propose a similar solution to the path taken with conda-build-all.

**Comment by kalefranz** [comment]
@jakirkham With #43 I think we should be set here.  With the three commits in that PR, I've ran the CI against both conda 4.2 and conda 4.3.

**Comment by jakirkham** [comment]
Thanks @kalefranz. Closing in favor of your more complete PR. 👍

**Pull request closed without merging**
